### PR TITLE
COCOS-181 - Add failed state for algo execution

### LINKED ISSUE #181: Feature: Transition to Different State on Failed Computation Run
### Is your feature request related to a problem? Please describe.

When computation run fails, agent produces an event indicating failed run, however, the next state after this is `resultsReady` which may mis-inform the user.

image

### Describe the feature you are requesting, as well as the possible use case(s) for it.

This will enhance the user experience and allow the user to know that the run failed, and no results are available.

### Indicate the importance of this feature to you.

Should-have

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SammyOina**
# What type of PR is this?
This a feature as it adds a new failed state to agent

## What does this do?
- **New Features**
	- Enhanced error handling with the introduction of a new error for consumed results.
	- Added support for failure states in the computation process.

- **Improvements**
	- Refined state machine logic to handle computation failures and transitions more effectively.
	- Improved clarity of comments and descriptions for better understanding of service behavior.

## Which issue(s) does this PR fix/relate to?

- Resolves #181 

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
Will update cocos docs

### CODE REVIEW

**Review by WashingtonKK — COMMENTED** [review]
@SammyOina 
What do you think about this:

When a user attempts to fetch results before they are ready, return a warning that results are not ready and do not transition to the next state on the state machine.

Can this also be handled in this PR?

**Comment by SammyOina** [comment]
> @SammyOina What do you think about this:
> 
> When a user attempts to fetch results before they are ready, return a warning that results are not ready and do not transition to the next state on the state machine.
> 
> Can this also be handled in this PR?

agent already returns results not ready warning. agent will not transition from running state unless results are ready or algo execution failed.

**Review by WashingtonKK — CHANGES_REQUESTED** [review]
image

We have two indications of failed, I would say we only have:

`Running -> Failed`

And remove: 

`Failed -> failed`

**Comment by SammyOina** [comment]
> image
> 
> We have two indications of failed, I would say we only have:
> 
> `Running -> Failed`
> 
> And remove:
> 
> `Failed -> failed`

Failed state exits for two reasons, one is for result consumers to see the reason for failed computation, another is to allow agent to remain in this state after running, it cannot remain in failed state perpetually. i.e running failed is not an actual state. agent state machine is still running. see https://github.com/SammyOina/cocos-ai/blob/cocos-181/agent/state.go

**Pull request merged**
