### PR TITLE
NOISSUE - Python runtime

### PR DESCRIPTION
**Pull request by SammyOina**
# What type of PR is this?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

### CODE REVIEW

**Comment by drasko** [comment]
@SammyOina please resolve the conflicts

**Comment by drasko** [comment]
I would like that we block this PR until we decide if we would like to mandate Docker as an algorithm execution isolate. If we mandate Docker, that we do not need to pollute Computation and Manifest with Requirements.

**Comment by SammyOina** [comment]
> I would like that we block this PR until we decide if we would like to mandate Docker as an algorithm execution isolate. If we mandate Docker, that we do not need to pollute Computation and Manifest with Requirements.

I had reported some of my findings on docker on this issue #134

**Comment by drasko** [comment]
Closing in favor of https://github.com/ultravioletrs/cocos/pull/178

**Pull request closed without merging**
